### ISSUE TITLE
runner is not going after first target

### ISSUE THREAD

**Issue by sdkshn** [Maprunner/rg2#223] opened 2015-01-18 18:45 UTC
I did all the settings. I drew the runner route but runner  does not continue after the first goal. I do not have mistakes when I transfer the route runner from GPX file. How do I solve this problem?

**Comment by Maprunner** [comment] 2015-01-18 20:18
Please can you provide a link so that I can see exactly what the problem is.

**Comment by sdkshn** [comment] 2015-01-18 22:10
Thank you for your help.Link:

http://biradam.tk/routegadget/rg2
When I load from GPX it works.
When I drew in "DRAW" tab it works not.

2015-01-18 22:18 GMT+02:00 Simon Errington <notifications@github.com>:

**Comment by sdkshn** [comment] 2015-01-19 05:24
Do you have any advice?

2015-01-19 0:10 GMT+02:00 sadık şahin <blacksimit0909@gmail.com>:

**Comment by Maprunner** [comment] 2015-01-19 19:29
I have just released a new version (1.0.0) which fixes this problem. If you install that then you should be able to use the replay function.

**Comment by sdkshn** [comment] 2015-01-19 23:55
thanks it works :)


2015-01-19 21:29 GMT+02:00 Simon Errington <notifications@github.com>:

**Comment by sdkshn** [comment] 2015-01-21 10:34
http://oryantiring.info/routegadget/rg2


I upload XML 3.0 from OCAD. The program is reading categories but unlike in
your manager intro-video. All of them is " 0 ". I upload a picture.



2015-01-20 1:55 GMT+02:00 sadık şahin <blacksimit0909@gmail.com>:

**Comment by Maprunner** [comment] 2015-01-21 19:45
Closed in version 1.0.0

**Closed by Maprunner** 2015-01-21 19:45 UTC
