### ISSUE TITLE
Route id changes as people add GPS tracks

### ISSUE THREAD

**Issue by JamesErrington** [Maprunner/rg2#360] opened 2017-05-09 18:16 UTC
http://forum.nopesport.com/viewtopic.php?f=1&t=15104

Means deeplinking to specific routes doesn't work

**Comment by Maprunner** [comment] 2017-05-11 10:03
Routes in the hash need to be referenced by resultid, but are being referenced by the results array index. The problem is that this value changes as people add GPS routes. Looks like the following changes are needed, all in results.js:

1. getTracksOnDisplay needs to return an array of resultid, not array index
2. putOneTrackOnDisplay needs to loop through results and test 
````
this.results[i].resultid === resultid
````
Careful that the parameter comes in as a string so you need to use parseInt(resultid, 10) to force it to an integer for the comparison
3. Similar changes for removeOneTrackFromDisplay
4. In formatResultListAsAccordion the id for showtrack needs to be resultid, not i

Unfortunately this breaks (most) existing links, but they are broken anyway so we can live with it.

**Comment by JamesErrington** [comment] 2017-05-11 10:21
Have you implemented this change in your branch?

**Comment by Maprunner** [comment] 2017-05-11 10:30
I was leaving it to you...

**Comment by JamesErrington** [comment] 2017-05-11 11:08
There's no dev branch to pull request into

**Comment by Maprunner** [comment] 2017-05-11 11:40
I've just recreated it.

**Comment by Maprunner** [comment] 2017-05-11 13:18
Now merged with dev and will go in 1.4.1.

**Closed by Maprunner** 2017-05-11 13:18 UTC
